name: RCM Job (12h)

on:
  schedule:
    - cron: '0 */12 * * *'  # Corre de 12 em 12 horas
  workflow_dispatch:        # Permite correr manualmente

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    - name: Install R packages
      run: |
        Rscript -e 'install.packages(c("jsonlite", "dplyr", "readr", "readxl"), repos="http://cran.us.r-project.org")'

    - name: Run R script
      run: Rscript script.R

    - name: Upload output CSV as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rcm_output
        path: rcm_d0.csv
