name: RCM Job (00h e 12h de Portugal)

on:
  schedule:
    - cron: '0 0,11 * * *'   # Corre às 01h e 12h de Portugal (UTC)
  workflow_dispatch:          # Permite execução manual

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Setup do R
      uses: r-lib/actions/setup-r@v2

    - name: Cache de pacotes R
      uses: actions/cache@v4
      with:
        path: ~/.cache/R/cran
        key: r-packages-${{ runner.os }}-${{ hashFiles('**/script.R') }}
        restore-keys: |
          r-packages-${{ runner.os }}-

    - name: Instalar pacotes R (usando cache)
      run: |
        mkdir -p ~/.cache/R/cran
        Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); install.packages(c("jsonlite", "dplyr", "readr", "readxl"), lib = "~/.cache/R/cran")'

    - name: Executar script R
      run: |
        echo 'Definir caminho da cache como biblioteca principal'
        echo '.libPaths("~/.cache/R/cran")' > .Rprofile
        Rscript script.R

    - name: Upload dos resultados como artifacts (opcional)
      uses: actions/upload-artifact@v4
      with:
        name: rcm_outputs
        path: |
          rcm_d0.csv
          metadata_rcm.json

    - name: Configurar Git para commit automático
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit e push se houver alterações
      run: |
        git add rcm_d0.csv metadata_rcm.json
        git diff --cached --quiet rcm_d0.csv metadata_rcm.json || (
          git commit -m "Atualização automática dos dados RCM [$(date '+%Y-%m-%d %H:%M')]"
          git push origin main
        )
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
