name: RCM Job (00h e 12h de Portugal)

on:
  schedule:
  - cron: '0 0,11 * * *'   # Corre às 01h e 12h de Portugal
  workflow_dispatch:          # Permite execução manual

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3
      with:
        persist-credentials: true   # ✅ Permite fazer push com GITHUB_TOKEN

    - name: Setup do R
      uses: r-lib/actions/setup-r@v2

    - name: Instalar pacotes R
      run: |
        Rscript -e 'install.packages(c("jsonlite", "dplyr", "readr", "readxl"), repos="http://cran.us.r-project.org")'

    - name: Executar script R
      run: Rscript script.R

    - name: Upload do CSV como artifact (opcional)
      uses: actions/upload-artifact@v4
      with:
        name: rcm_output
        path: rcm_d0.csv

    - name: Configurar Git para commit automático
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit e push do CSV se houver alterações
      run: |
        if [ -f "rcm_d0.csv" ]; then
          git add rcm_d0.csv
          git diff --cached --quiet rcm_d0.csv || (
            git commit -m "Atualização automática do rcm_d0.csv [$(date '+%Y-%m-%d %H:%M')]"
            git push origin main
          )
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
